@Hostname = localhost
@Port = 5219
@Host = http://{{Hostname}}:{{Port}}

### 1. Create a Product
# @name createProduct
POST {{Host}}/api/products
Content-Type: application/json

{
  "name": "Mechanical Keyboard",
  "price": 149.99,
  "sku": "KBD-001-RGB"
}

### 2. Create Product with Invalid Price (Validation Test)
POST {{Host}}/api/products
Content-Type: application/json

{
  "name": "Cheap Mouse",
  "price": -10.00,
  "sku": "MSE-002"
}

### 3. Get Non-Existent Product (NotFound Test)
GET {{Host}}/api/products/3134c4dc-1974-47ac-85b3-f4e6203adcaa
Accept: application/json
