@Host = http://localhost:5219
@ApiBase = {{Host}}/api/products

# @name CreateProduct
POST {{ApiBase}}
Content-Type: application/json

{
  "name": "Gaming Mouse",
  "price": -10,
  "sku": "MOUSE-001"
}

# @name GetProductById
GET {{ApiBase}}/419457d1-00b6-439f-aac9-dfd1e08e9ec1
Accept: application/json

###
